


###
@EVENT_ID = 1024874548
@BASE_URL = http://localhost:8000

# Health Check
GET {{BASE_URL}}/


###

# Get docs
GET {{BASE_URL}}/docs


###

# Collect Odds Data
POST {{BASE_URL}}/collect



###

# Get all Events
GET {{BASE_URL}}/events/


###
# Get a specific Event by ID
GET {{BASE_URL}}/event/{{EVENT_ID}}



###
# Get teams
GET {{BASE_URL}}/teams



###
# Get team events
GET {{BASE_URL}}/team/KC/events



###
# Get a specific Event by ID
GET {{BASE_URL}}/event/{{EVENT_ID}}/offers


###
# Get a specific Event by ID
GET {{BASE_URL}}/event/{{EVENT_ID}}/offers?range=true



###
# Get a Event MoneyLine
GET {{BASE_URL}}/event/{{EVENT_ID}}/offers/moneyline/


###
# Get a Event Handicap
GET {{BASE_URL}}/event/{{EVENT_ID}}/offers/handicap/



###
# Get a Event OverUnder
GET {{BASE_URL}}/event/{{EVENT_ID}}/offers/overunder/


###

# Get all Bet Offers for a specific Event
GET {{BASE_URL}}/event/{{EVENT_ID}}/offers


###

# Get all changes across all events
GET {{BASE_URL}}/changes