


###
#
#
#
@BASE_URL = http://localhost:{{ $dotenv APP_PORT }}
# Health Check
GET {{BASE_URL}}/
###
# Test Prometheus Endpoint
GET {{BASE_URL}}/metrics
###
# Get docs
GET {{BASE_URL}}/docs
###
# Get docs
GET {{BASE_URL}}/openapi.json
#
#
#
#
#
#
@EVENT_ID = 1024875948
###
#
# Collect Odds Data
PUT {{BASE_URL}}/collect

###
#
# Collect Odds Data
PUT {{BASE_URL}}/collect/?provider_key=theoddsapi


###

# Get all Events
GET {{BASE_URL}}/events/

###
# Get a specific Event by ID
GET {{BASE_URL}}/event/{{EVENT_ID}}

###
# Get teams
GET {{BASE_URL}}/teams



###
# Get team events
GET {{BASE_URL}}/team/KC/events

###
# Get a specific Event by ID
GET {{BASE_URL}}/event/{{EVENT_ID}}

###
# Get a specific Event by ID
GET {{BASE_URL}}/event/{{EVENT_ID}}/offer/h2h


###
# Get a specific Event by ID
GET {{BASE_URL}}/event/{{EVENT_ID}}/offers?range=true



###
# Get a Event MoneyLine
GET {{BASE_URL}}/event/{{EVENT_ID}}/offers/moneyline/


###
# Get a Event Handicap
GET {{BASE_URL}}/event/{{EVENT_ID}}/offers/handicap/



###
# Get a Event OverUnder
GET {{BASE_URL}}/event/{{EVENT_ID}}/offers/overunder/


###

# Get all Bet Offers for a specific Event
GET {{BASE_URL}}/event/{{EVENT_ID}}/offers


###

# Get all changes across all events
GET {{BASE_URL}}/changes